const ACTION_TYPES = {
    INCREASE_ITEM: "INCREASE_ITEM",
    DECREASE_ITEM: "DECREASE_ITEM",
    ADD_ITEM: "ADD_ITEM",
    UPDATE_ITEM: "UPDATE_ITEM",
    DELETE_ITEM: "DELETE_ITEM",
    ARCHIVE_ITEM: "ARCHIVE_ITEM"
};

export default ACTION_TYPES;