const ACTION_TYPES = {
    INCREASE_ITEM: "INCREASE_ITEM",
    INCREASE_ITEM_C1: "INCREASE_ITEM_C1",
    INCREASE_ITEM_C2: "INCREASE_ITEM_c2",
    RESET_COUNTER: "RESET_COUNTER",
    DECREASE_ITEM: "DECREASE_ITEM",
    ROOT_CHANGED: "ROOT_CHANGED",

    // TODO LIST ACTIONS
    ADD_ITEM: "ADD_ITEM",
    UPDATE_ITEM: "UPDATE_ITEM",
    DELETE_ITEM: "DELETE_ITEM",
    TOGGLE_ITEM_COMPLETE: "TOGGLE_ITEM_COMPLETE",
    ARCHIVE_ITEM: "ARCHIVE_ITEM"
};

export default ACTION_TYPES;