const ACTION_TYPES = {
    INCREASE_ITEM: "INCREASE_ITEM",
    INCREASE_ITEM_C1: "INCREASE_ITEM_C1",
    INCREASE_ITEM_C2: "INCREASE_ITEM_c2",
    DECREASE_ITEM: "DECREASE_ITEM",
    ADD_ITEM: "ADD_ITEM",
    UPDATE_ITEM: "UPDATE_ITEM",
    DELETE_ITEM: "DELETE_ITEM",
    ARCHIVE_ITEM: "ARCHIVE_ITEM",
    ROOT_CHANGED: "ROOT_CHANGED"
};

export default ACTION_TYPES;